/**
 * SI derived units (2.2 Table 3)
 */
module.exports = [
    {   
        system: 'SI',
        quantity: 'plane angle', 
        name: 'radian', 
        symbol: 'rad', 
        other: '1', 
        base: 'm/m' },
    {   
        system: 'SI',
        quantity: 'solid angle', 
        name: 'steradian', 
        symbol: 'sr',
        other: '1',
        base: 'm²/m²' },
    { 
        system: 'SI',
        quantity: 'frequency', 
        name: 'hertz', 
        symbol: 'Hz', 
        base: 's⁻¹' },
    {   
        system: 'SI',
        quantity: 'force', 
        name: 'newton', 
        symbol: 'N', 
        base: 'm kg s⁻²' },
    { 
        system: 'SI',
        quantity: 'pressure, stress',
        name: 'pascal', 
        symbol: 'Pa', 
        other: 'N/m²', 
        base: 'm⁻¹ kg s⁻²' },
    { 
        system: 'SI',
        quantity: 'energy, work, amount of heat', 
        name: 'joule', symbol: 'J', 
        other: 'N m', 
        base: 'm² kg s⁻²' },
    { 
        system: 'SI',
        quantity: 'power, radiant flux', 
        name: 'watt', 
        symbol: 'W', 
        other: 'J/s', 
        base: 'm² kg s⁻³' },
    { 
        system: 'SI',
        quantity: 'electric charge, amount of electricity', 
        name: 'coulomb', 
        symbol: 'C', 
        base: 's A' },
    { 
        system: 'SI',
        quantity: 'electric potential difference, electromotive force', 
        name: 'volt', 
        symbol: 'V', 
        other: 'W/A',
        base: 'm² kg s⁻³ A⁻¹' },
    { 
        system: 'SI',
        quantity: 'capacitance', 
        name: 'farad', 
        symbol: 'F', 
        other: 'C/V', 
        base: 'm⁻² kg⁻¹ s⁴ A²' },
    { 
        system: 'SI',
        quantity: 'electric resistance', 
        name: 'ohm', 
        symbol: 'Ω', 
        other: 'V/A', 
        base: 'm² kg s⁻³ A⁻²' },
    { 
        system: 'SI',
        quantity: 'electric conductance', 
        name: 'siemens', 
        symbol: 'S', 
        other: 'A/V', 
        base: 'm⁻² kg⁻¹ s³ A²' },
    { 
        system: 'SI',
        quantity: 'magnetic flux', 
        name: 'weber', 
        symbol: 'Wb', 
        other: 'V s', 
        base: 'm² kg s⁻² A⁻¹' },
    { 
        system: 'SI',
        quantity: 'magnetic flux density', 
        name: 'tesla', 
        symbol: 'T', 
        other: 'Wb/m²', 
        base: 'kg s⁻² A⁻¹' },
    { 
        system: 'SI',
        quantity: 'inductance', 
        name: 'henry', 
        symbol: 'H', 
        other: 'Wb/A', 
        base: 'm² kg s⁻² A⁻²' },
    { 
        system: 'SI',
        quantity: 'Celsius temperature', 
        name: 'degree Celsius', 
        symbol: '°C',
        base: 'K' },
    { 
        system: 'SI',
        quantity: 'luminous flux', 
        name: 'lumen', 
        symbol: 'lm', 
        other: 'cd sr', 
        base: 'cd' },
    { 
        system: 'SI',
        quantity: 'illuminance', 
        name: 'lux', 
        symbol: 'lx', 
        other: 'lm/m²', 
        base: 'm⁻² cd' },
    { 
        system: 'SI',
        quantity: 'activity referred to a radionuclide', 
        name: 'becquerel', 
        symbol: 'Bq', 
        base: 's⁻¹' },
    { 
        system: 'SI',
        quantity: 'absorbed dose, specific energy (imparted), kerma', 
        name: 'gray',
        symbol: 'Gy', 
        other: 'J/kg', 
        base: 'm² s⁻²' },
    { 
        system: 'SI',
        quantity: 'dose equivalent, ambient dose equivalent, directional dose equivalent, personal dose equivalent', 
        name: 'sievert', 
        symbol: 'Sv', 
        other: 'J/kg', 
        base: 'm² s⁻²' },
    { 
        system: 'SI',
        quantity: 'catalytic activity', 
        name: 'katal', 
        symbol: 'kat',
        base: 's⁻¹ mol' },
];
