language: node_js
env: CI=true
node_js:
- stable
before_script:
- npm install -g gulp
script:
- gulp release
- pkg=$(npm pack)
- npm install -g $pkg
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7e10c857f561d459ceb7
    on_success: change
    on_failure: always
    on_start: never
deploy:
  - provider: npm
    skip_cleanup: true
    email: makaretu@gmail.com
    api_key:
      secure: oS9GJPBRgZshpLyblD3BxJi/fOtWmeUpYU0R4vi+6vOvFaPXCJPUfIwB6zwO1W7bl2PCzIHKXS2lS1jC+pvV59gnYV2NLLKG4CIWMN47FDIJj6oVRo+M+4q8ETUZBTIEBbU/WrO+8g9Jsx6DuWaRtVkgxcJqMuSJDlJXIGQg5BSbHfMZShTAIp3zimSQ87xC5/3KyEmuVZjPfIbkp5DNRZMsOJn9sfxLwB5BNJvouV+IarlEMZXraljTSJmrvUDSiRrq0GSeTc3hz7XK7mWhZVgS7lvIYJYjA/3yKvQZBTzbNX4EUdpcNERkJLIa2zC+91hqC+Uf1E70pOTxi81TBF7JXdfXKYDI6xXj+FI8sSpsHMJOnQ4S9UK1Jj68EdmhAstmwKvLUcd5Bvj7IEsB/JkW16xTZJVxFfneDXpnJmOT/KnwgHeKsAzgqYWo0CEwRCIByAevS8i9VRThbK41cE/0xF3kNA+Fx5hFRLQHfwgISLTHr0P79ZrBlXaduQJVjOY7URfLj2+7fvUWeBV4fjzsxaINVGepAZPckEQrUdw8RhQTJ2WmSjQgCS+m/JgVYLvwdzIcA9nn/qththbbH6Ye4yLbhBcLUPkb3LZH017e2CTDX3lQAygHW1gWo0dtVNVoZwnPN1qyBGcEKpOztj1aIImXefNen2o22bDZvyA=
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: UM+VEoCmFiXbdIwAN5ULovgtNiItjr9+KEBOH4EOJ88/t0EbjpTvTzsAoidmvPUoO75F+oq2DFWmbySfIc0xpgFMxs7iCssjpMBjhykLq8G6kz0vn/mRo2GElUlidWFmtW9oBEBVgqZE77Bj/9VBdndJPVgWUgbuIoUgY9TIe2NAGZH28aq/vwh93l6Zjw55jQrIXBYTQKUbby41qfgyWPpETlEj1jyZmqu0E7G4AuecJBP9FYzG2i/26anG+wbMsp86MucLcezCWeRGjo+IJI7ZCHXs2AtK060B7DnVxSOcKUsDgiV2aY6tM3phcURDX+RruzRYxZ9ufqWjpt+yDeEucBgPd8xHIYgAahwnVBhPEmqsqscfUuwV3oWGGok78YfVyDETeKr5rAGk0YSTJ8QZ5iko2RMEQGglZU2ZOT7c4eT8xxoWuryAdQdzxy4/Ll/TlS/T1Xlk3jkPgoOYqyfbzZ6vmTY2BBsXtY4O/f4b4hwUUqrkvZMVn4GExLWJH/IZdvagitrStfFhIkIuHCDGDUzXiJbc/V4CzNdE3YaJXamjNARA/B23SlbfCocaw4oC+UTpfqSpTQ0heMyvHVxWcc6curc++WvnGYJeFcmw5UTBjNv1QievptR862lZUbrq2VJR1auskhpJQmoUIZB8VRDukoS07rvD3JwIsU0=
    file: package.json
    on:
      repo: richardschneider/isq
      branch: master
