sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e10c857f561d459ceb7
    on_success: change
    on_failure: always
    on_start: never
node_js:
  - stable
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - gulp
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
