language: node_js
env: CI=true
node_js:
- stable
before_script:
- npm install -g gulp
script:
- gulp
- pkg=$(npm pack)
- npm install -g $pkg
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7e10c857f561d459ceb7
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: makaretu@gmail.com
  api_key:
    secure: oS9GJPBRgZshpLyblD3BxJi/fOtWmeUpYU0R4vi+6vOvFaPXCJPUfIwB6zwO1W7bl2PCzIHKXS2lS1jC+pvV59gnYV2NLLKG4CIWMN47FDIJj6oVRo+M+4q8ETUZBTIEBbU/WrO+8g9Jsx6DuWaRtVkgxcJqMuSJDlJXIGQg5BSbHfMZShTAIp3zimSQ87xC5/3KyEmuVZjPfIbkp5DNRZMsOJn9sfxLwB5BNJvouV+IarlEMZXraljTSJmrvUDSiRrq0GSeTc3hz7XK7mWhZVgS7lvIYJYjA/3yKvQZBTzbNX4EUdpcNERkJLIa2zC+91hqC+Uf1E70pOTxi81TBF7JXdfXKYDI6xXj+FI8sSpsHMJOnQ4S9UK1Jj68EdmhAstmwKvLUcd5Bvj7IEsB/JkW16xTZJVxFfneDXpnJmOT/KnwgHeKsAzgqYWo0CEwRCIByAevS8i9VRThbK41cE/0xF3kNA+Fx5hFRLQHfwgISLTHr0P79ZrBlXaduQJVjOY7URfLj2+7fvUWeBV4fjzsxaINVGepAZPckEQrUdw8RhQTJ2WmSjQgCS+m/JgVYLvwdzIcA9nn/qththbbH6Ye4yLbhBcLUPkb3LZH017e2CTDX3lQAygHW1gWo0dtVNVoZwnPN1qyBGcEKpOztj1aIImXefNen2o22bDZvyA=
  on:
    branch: master
