sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - gulp
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
